### ISSUE TITLE
Nested id fields populates incorrect query

### ISSUE THREAD

**Issue by Metamist** [feathersjs-ecosystem/feathers-authentication-hooks#22]
I'm having an issue with `queryWithCurrentUser` and `restrictToOwner` with RethinkDB (probably unrelated to RethinkDB). 

### Steps to reproduce
Pass a nested field name to it, for example `primary_owner.id`.

Here's the hook used. Also happens with `queryWithCurrentUser` and `as` field.
```
  before: {
    find: [
      authHooks.restrictToOwner({ idField: 'id', ownerField: 'primary_owner.id' }),
      (hook) => {
        debug('-------- BEFORE FIND');
        debug(hook.params.query); // New 
      }
    ],
```
Resulting query:
```
{ primary_owner: { id: '76561198020019152' } }
```

RethinkDB doesn't seem to handle actual nested objects, it handles it through the `.` key

### Expected behavior
The resulting query should become `query: { 'primary_owner.id': '<user id>' }`. 

### Actual behavior
The resulting query turns into `query: { primary_owner: { id: '<user id>' } }`.

### System configuration

**Module versions**: `feathers-authentication-hooks: 0.1.4`, `feathers-rethinkdb: 0.4.3`

**NodeJS version**: `v7.7.4`

**Operating System**: `Windows 8.1`

**Module Loader**: `Webpack 3.2.0`

**Comment by jus101** [comment]
I'm seeing a similar problem when using Mongoose:
Schema:
```
const Organisation = new Schema({
    name: { required: true, type: String },
    users: [{ user: { type: Schema.Types.ObjectId, ref: 'users' }]
  });
```
Hook:
```
before: {
  all: [ restrictToOwner({ ownerField: 'users.user' }) ]
}
```
Resulting Mongoose query when doing a GET:
```
Mongoose: organisations.find({ users: { _id: ObjectId("59cc33bbef5e3afe02e7b8a3"), user: ObjectId("59cc33baef5e3afe02e7b89d") } }, { fields: {} })
```
Expected query:
```
Mongoose: organisations.find({ 'users.user': ObjectId("59cc33baef5e3afe02e7b89d") }, { fields: {} })
```

**Comment by jus101** [comment]
I think the problem stems from the use of lodash.set:
https://github.com/feathersjs/feathers-authentication-hooks/blob/ee4630b9cf3aed37a2f6341c7f9de9d9628e7daf/src/query-with-current-user.js#L31

Maybe introduce an option `expandPaths = true `; To fix this problem with RethinkDB / Mongoose, you'd set `expandPaths: false`?
