### ISSUE TITLE
[feature request] `restrictToRole` can support `ownerField` as array, just like `restrictToOwner`

### ISSUE THREAD

**Issue by beeplin** [feathersjs-ecosystem/feathers-authentication-hooks#39]
In `restrictToOwner` the value of the owner field can be an array: 

https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/master/src/restrict-to-owner.js#L69-L76

```js
     if (Array.isArray(field)) {
        const fieldArray = field.map(idValue => idValue.toString());
        if (fieldArray.length === 0 || fieldArray.indexOf(id.toString()) < 0) {
          throw new errors.Forbidden('You do not have the permissions to access this.');
        }
      } else if (field === undefined || field.toString() !== id.toString()) {
        throw new errors.Forbidden('You do not have the permissions to access this.');
      }
```
But `restrictToRole` has a very similar API but currently doesn't support array:

https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/master/src/restrict-to-roles.js#L89-L91

```js
    if (field === undefined || field.toString() !== id.toString()) {
      throw new errors.Forbidden('You do not have the permissions to access this.');
    }
```

I wonder if this difference is an intentional design or not. If not, I could make a PR to improve it.

**Comment by daffl** [comment]
Closed via #40
