### ISSUE TITLE
restrictToOwner unexpected behaviour

### ISSUE THREAD

**Issue by rybaczewa** [feathersjs-ecosystem/feathers-authentication-hooks#48]
There seems to be some inconsistency between `restrictToOwner` hook documentation and behaviour.

[Readme states it can be used with any method](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks#restricttoowner)

[Looking at source code, there is an error thrown when method is not `get / patch / update / remove`](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/master/lib/restrict-to-owner.js#L33)

Not sure whether that's just an outdated readme or code that was supposed to be removed after some changes.

Current conditions don't allow usage on `create` method, and therefore on `all` as well.

**Comment by saiichihashimoto** [comment]
Well, it makes sense not to be on create, right? With `find / get / patch / update / remove`, there are resources to check against. With create, there's no resource to check against (not yet).

**Comment by rybaczewa** [comment]
Sure, but it might as well, underneath, use `associateCurrentUser` on create. Just making sure if that's an overlook in docs or some unexpected behaviour.
