### ISSUE TITLE
 Error: There is no current user to associate.

### ISSUE THREAD

**Issue by abalad** [feathersjs-ecosystem/feathers-authentication-hooks#49]
When using the `queryWithCurrentUser `command, if you change the `entity `in the FeatherJs settings, it generates the error below

`error:  Error: There is no current user to associate.
    at Object.<anonymous> (E:\Projetos\OTISEG\WEBSERVICE\mongo\node_modules\feathers-authentication-hooks\lib\query-with-current-user.js:20:13)
    at promise.then.hookObject (E:\Projetos\OTISEG\WEBSERVICE\mongo\node_modules\@feathersjs\commons\lib\hooks.js:167:73)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

In my opinion if FeatherJs allows to change the entity all the plugins should respect the configuration instead of having something fixed like:

```javascript
.... query-with-current-user.js 
  return function (hook) {
    if (hook.type !== 'before') {
      throw new Error('The \'queryWithCurrentUser\' hook should only be used as a \'before\' hook.');
    }

    if (!hook.params.user) // I think here should use the ENTITY configuration {
      if (!hook.params.provider) {
        return hook;
      }

      throw new Error('There is no current user to associate.');
    }
```

**Comment by daffl** [comment]
Basically the hardcoded `.user` in https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/master/lib/query-with-current-user.js#L15 and https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/master/lib/query-with-current-user.js#L25 should be a variable and probably use the authentication configuration.

**Comment by abalad** [comment]
Can this problem be corrected in the future?
