### ISSUE TITLE
restrictToRoles not returning current user's resources

### ISSUE THREAD

**Issue by davidcushing** [feathersjs-ecosystem/feathers-authentication-hooks#53]
### Steps to reproduce

Have implemented the restrictToRoles hook as follows. When the user requests resources, none are returned.

```
hooks.restrictToRoles({
      roles: ['admin:all'],
      fieldName: 'permissions',
      idField: '_id',
      ownerField: 'owner',
      owner: true
    })

```
If the user has the 'admin:all' role then all of the resources are returned. Otherwise, none are returned. Have I misread the documentation? The owner field was definitely set correctly.

### Expected behavior
I expect the list of resources returned to include any where the 'owner' property is set to the current user's '_id'. 

### Actual behavior
No resources are returned, unless the current user has the permission 'admin:all', in which case all resources are returned as expected.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

`feathers-authentication-hooks@0.2.0`

### Additional test

I created this hook to provide the expected behaviour...
If the user is not an 'admin:all' user then a param is added to the query to only return the current user's resources. This works as expected, and as I was expecting the 'restrictToRoles' hook to work. 

```
function onlyReturnUsersEvents(context){
  if (context.params.user.permissions){
    if (context.params.user.permissions.indexOf('admin:all')==-1){
      context.params.query.owner = context.params.user._id;
      console.log('not an admin');
    } 
  } else {
    context.params.query.owner = context.params.user._id;
  }
}
```

**Comment by daffl** [comment]
This hook will probably be deprecated because [feathers-permissions](https://github.com/feathersjs-ecosystem/feathers-permissions) is doing this better and more flexibly.

**Comment by davidcushing** [comment]
Thank you for the help/advice and updates! Much appreciated.
