### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by arfanliaqat** [feathersjs-ecosystem/feathers-authentication-hooks#69]
### Steps to reproduce
Visit https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/blob/hooks.md

### Expected behavior
It should work

### Actual behavior
Serve a 404

**Comment by daffl** [comment]
It should be https://docs.feathersjs.com/api/hooks.html. You can edit the page directly to submit a PR [here](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/edit/master/README.md).

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs-ecosystem/feathers-authentication-hooks/pull/73
