### ISSUE TITLE
Service with option Multi on create

### ISSUE THREAD

**Issue by klaus1978** [feathersjs-ecosystem/feathers-authentication-hooks#79]
### Steps to reproduce

Hi *,
I try to use setField on a service which was configured to be used for multiple document creation:

```
const options = {
    Model,
    paginate,
    multi: ['create']
  };
```
I now have a problem to set "setField correctly:

```
before:{
    create: [
      setField({
        from: 'params.user._id',
        as: 'data.owner'
      })
]
}
```
The problem is, that data is not an object anymore, it is an array...

No idea how to set that correctly...

Thanks in advance
Klaus

**Comment by adhityasan** [comment]
> ### Steps to reproduce
> Hi *,
> I try to use setField on a service which was configured to be used for multiple document creation:
> 
> ```
> const options = {
>     Model,
>     paginate,
>     multi: ['create']
>   };
> ```
> 
> I now have a problem to set "setField correctly:
> 
> ```
> before:{
>     create: [
>       setField({
>         from: 'params.user._id',
>         as: 'data.owner'
>       })
> ]
> }
> ```
> 
> The problem is, that data is not an object anymore, it is an array...
> 
> No idea how to set that correctly...
> 
> Thanks in advance
> Klaus

Hi, maybe u could apply this... here's some example code of my custom hooks when I try to add UUID to each data in the context  
```
return async (context) => {
    if (context.service?.options?.multi && Array.isArray(context.data)) {
        if (
            context.service.options.multi === true ||
            (Array.isArray(context.service?.options?.multi) &&
                [...context.service.options.multi].includes(context.method))
        ) {
            context.data.forEach((d) => {
                d.id = uuid();
            });
         
            return context;
        }
    }

    context.data.id = uuid();
    return context;
}
```

**Comment by adhityasan** [comment]
@klaus1978 So basically you could just create some custom hooks and loop the setField to each data
